[package]
name = "mydiary"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.49", features = ["derive", "cargo"] }
directories = "6.0.0"
textwrap = "0.16.2"
